browser=chrome
chrome_path=/Drivers/chromedriver
chrome_property=webdriver.chrome.driver
url=https://myoona.ph/
// Gmail SMTP server configuration


#environment is case sensitive , refer ( prod, uat,preprod keywords to change envirnment)
environment=prod

host =smtp.gmail.com
port =587
smtpAuthentication=mail.smtp.auth
tlsEncription=mail.smtp.starttls.enable
smtpHost=mail.smtp.host
smtpPort=mail.smtp.port
smtpCertificate=mail.smtp.ssl.trust

username =kanchan.tambe@deptagency.com
password =tenz veou hjud nqbm

wait=80
scrollWait=80
elewait =80

// DriverManager
headlessBrowserSize=window-size=1920,1080
sandBox=no-sandbox
runHeadless=--headless
url=https://buyonlineuat.indiafirstlife.com/ulip-plans/indiafirst-life-radiance-smart-invest-plan
fullname=Amit Mishra
dob=12121993
mobno=7848516677
emailid=amitmishra@gmail.com
birthDay=1993-12-12
birthdateabelow8years=2023-12-12
birthdateabove8years=2015-12-12
